/*
 * Copyright (c) 2013 Samsung Electronics Co., Ltd.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

/**
 * @file eail-explorer-tr.h
 *
 * @brief Defines the various strings for Eail Explorer
 */

#define ACC_DESC "Accessible description"
#define ACC_DESC_TO_SET "Accessible des. to set"
#define ACC_NAME "Accessible name"
#define ACC_NAME_TO_SET "Accessible name to set"
#define ACC_ROLE "Accessible role"
#define ACC_STATES "Accessible states"
#define ACC_TYPE "Accessible type"
#define ACTION_DESC "Action description"
#define ALPHA "Alpha"
#define BOTTOM "Bottom"
#define CARET_OFFSET "Caret offset"
#define CHANGE_IMG "Change image"
#define CHANGE_POS "Change position"
#define CHAR_AT_OFFSET "Character at offset"
#define CHAR_COUNT "Character count"
#define CLEAR_SEL "Clear selection"
#define CLIENT_INIT "EAIL Client Hook initialized"
#define COPY "Copy"
#define COPY_TEXT_DESCRIPTION "(use sliders to specify start and end position)"
#define CURR_VAL "Current value"
#define CUT "Cut"
#define CUT_TEXT "Cut text"
#define DO_ACTION "Do action"
#define EAIL_EXPLORER "EAIL-EXPLORER"
#define EMPTY_PATH "Path is empty"
#define END_OFFSET "End offset"
#define END_POINT "End point"
#define ENTER_DESC "Enter description"
#define ENTER_NAME "Enter name"
#define ENTER_VAL "Enter value"
#define ENTER_TXT "Enter text"
#define ERR_ACTION "Get actions number failed"
#define ERR_FATAL "EAIL Client fatal error: not an Elementary application"
#define ERR_SET_POSITION "Set position failed"
#define ERR_GET_POSITION "Get position failed"
#define ERR_ATK_LAYER "Set atk_layer failed"
#define ERR_ATK_ALPHA "Set atk alpha failed"
#define ERR_MDI_ZORDER "Get atk_mdi_zorder number failed"
#define ERR_OBJECT_INDEX "Get object index in parent failed"
#define ERR_CHILD_COUNT "Get children count failed"
#define ERR_ROW "Get row number failed"
#define ERR_COLUMN "Get column number failed"
#define ERR_SELECTION "Get selection number failed"
#define ERR_DESCRIPTION "Set description failed"
#define ERR_PRINT_GVALUE "Print GValue failed"
#define ERR_GET_CHAR_OFFSET "Get character at offset failed"
#define ERR_TEXT_CARET "Get text caret offset failed"
#define ERR_CHAR_COUNT "Get character count failed"
#define ERR_N_SELECTIONS "Get text n selections failed"
#define ERR_WRITE_STATES "Error occured during writing states"
#define ERR_MEMORY "Memory allocation failed"
#define EXISTS "Exists"
#define FAIL_OCC "Failure occurred"
#define HEIGHT "Height"
#define IMG_BORDER "Image border"
#define IMG_DESC "Image description"
#define IMG_FILE "Image file"
#define IMG_LOCALE "Image locale"
#define IMG_POS "Image position"
#define IMG_SIZE "Image size"
#define INDEX_IN_PAR "Index in parent"
#define INDEX_ERR "Index error"
#define LAYER "Layer"
#define LEFT "Left"
#define MAP "Map"
#define MAX_VAL "Max value"
#define MDI_ZORDER "Mdi zorder"
#define MIN_INC "Min increment"
#define MIN_VAL "Min value"
#define NEXT_COL "Next column"
#define NEXT_ROW "Next row"
#define NO_DESC "No description"
#define NO_LOCALE "Does not have locale"
#define NO_NAME "No name"
#define NO_PAR "No parent"
#define NO_STATES "No states"
#define NOT_EXISTS "Does not exist"
#define NUM_OF_ACTIONS "Number of actions"
#define NUM_OF_CHILDREN "Number of children"
#define NUM_OF_COLS "Number of columns"
#define NUM_OF_RELATIONS "Number of relations"
#define NUM_OF_ROWS "Number of rows"
#define NUM_OF_SEL_CHLD "Number of selected children"
#define NUM_OF_SEL_REGIONS "Number of selected regions"
#define OFFSET "Offset"
#define PAR_ACC_NAME "Parent accessible name"
#define PAR_ACC_TYPE "Parent accessible type"
#define PASTE "Paste"
#define PASTE_TEXT "Paste text"
#define POS_IN_WIN "Position in window"
#define POS_ON_SCREEN "Position on screen"
#define PREV_COL "Previous column"
#define PREV_ROW "Previous row"
#define RESIZE "Resize"
#define RIGHT "Right"
#define SEL "Select"
#define SEL_ALL_CHILDREN "Select all children"
#define SEL_COL_DESC "Selected column description"
#define SEL_FIRST_CHILD "Select first child"
#define SEL_LAST_CHILD "Select last child"
#define SEL_NEXT_CHILD "Select next child"
#define SEL_NEXT_COL "Select next column"
#define SEL_NEXT_ROW "Select next row"
#define SEL_PREV_CHILD "Select previous child"
#define SEL_PREV_COL "Select previous column"
#define SEL_PREV_ROW "Select previous row"
#define SEL_ROW_DESC "Selected row description"
#define SET "Set"
#define SET_IMG_DESC "Set image description"
#define SET_SEL "Set selection"
#define SET_SEL_COL_DESC "Set selected column description"
#define SET_SEL_ROW_DESC "Set selected row description"
#define SET_DESC "Set description"
#define SET_DESC_ERR "Set description error"
#define SET_NAME "Set name"
#define SET_SIZE "Set size"
#define SET_OFFSET "Set offset"
#define SET_VAL "Set value"
#define SIZE "Size"
#define START_OFFSET "Start offset"
#define START_POINT "Start point"
#define TEXT_VAL "Text"
#define TXT_SPIN_USAGE "Use offset spinner to specify index"
#define SET_TEXT "Set Text"
#define TOP "Top"
#define UNSET "Unset"
#define USAGE "(use spinners to set regions and offsets)"
#define VAL "Value"
#define VAL_TOO_HIGH "Value is too high"
#define WIDGET_NAME "Widget name"
#define WIDTH "Width"
#define X "X"
#define Y "Y"
